// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var App = require("./app.js");
var Http = require("http");
var SocketIo = require("socket.io");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var port = "3000";

App.app.set("port", port);

var server = Http.createServer(App.app);

var io = SocketIo(server);

server.listen(port);

server.on("error", (function (error) {
        throw [
              Caml_builtin_exceptions.failure,
              "oh no " + error.code
            ];
      }));

server.on("listening", (function (param) {
        console.log("Server started ...");
        return /* () */0;
      }));

exports.port = port;
exports.server = server;
exports.io = io;
/*  Not a pure module */
