// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as Caml_option from "../node_modules/bs-platform/lib/es6/caml_option.js";

function $great$great$eq(a, f) {
  if (a !== undefined) {
    return Curry._1(f, Caml_option.valFromOption(a));
  }
  
}

function $$default(value, $$default$1) {
  if (value !== undefined) {
    return Caml_option.valFromOption(value);
  } else {
    return $$default$1;
  }
}

function default_($$default, value) {
  if (value !== undefined) {
    return Caml_option.valFromOption(value);
  } else {
    return $$default;
  }
}

export {
  $great$great$eq ,
  $$default ,
  $$default as default,
  default_ ,
  
}
/* No side effect */
