// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function $great$great$eq(a, f) {
  if (a !== undefined) {
    return Curry._1(f, Caml_option.valFromOption(a));
  }
  
}

function $$default(value, $$default$1) {
  if (value !== undefined) {
    return Caml_option.valFromOption(value);
  } else {
    return $$default$1;
  }
}

function default_($$default, value) {
  if (value !== undefined) {
    return Caml_option.valFromOption(value);
  } else {
    return $$default;
  }
}

exports.$great$great$eq = $great$great$eq;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
exports.default_ = default_;
/* No side effect */
